Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -22,12 +22,16 @@ jobs:
           java-version: 21
           distribution: "microsoft"
       - run: |
+          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo apt-key add -
+          sudo curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
+          sudo apt update &>/dev/null && sudo apt install playit &>/dev/null && echo "Playit.gg installed" || echo "Failed to install playit"
+          
           wget https://api.papermc.io/v2/projects/paper/versions/1.20.6/builds/147/downloads/paper-1.20.6-147.jar
           echo "eula=true" >> eula.txt
-          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
-          chmod +x cloudflared-linux-amd64
+          # wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
+          # chmod +x cloudflared-linux-amd64
           echo "eula=true" > eula.txt
-          ./cloudflared-linux-amd64 tunnel --url tcp://127.0.0.1:25565 & java -jar paper-1.20.6-147.jar nogui
+          playit & java -jar paper-1.20.6-147.jar nogui
           
         
         
